clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    - landing-page
    - coffeeshop-store
    - quarkuscoffeeshop-cicd
    - quarkuscoffeeshop-demo

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management

    pipelines:
      name: openshift-pipelines-operator-rh

    amqstreams:
      name: amq-streams
      namespace: openshift-operators

    crunchypgo:
      name: crunchy-postgres-operator
      namespace: openshift-operators
      source: certified-operators

  projects:
    - hub
    - coffeeshop-store
    - quarkuscoffeeshop-demo

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    quarkuscoffeeshop-cicd:
      name: quarkuscoffeeshop-cicd
      namespace: quarkuscoffeeshop-cicd
      project: hub
      path: charts/hub/quarkuscoffeeshop-pipelines

    landing-page:
      name: landing-page
      namespace: landing-page
      project: hub
      path: charts/all/landing-page

    # Test coffeeshop (hub)
    coffeeshop-test:
      name: quarkuscoffeeshop-demo
      namespace: quarkuscoffeeshop-demo
      project: quarkuscoffeeshop-demo
      path: charts/store/quarkuscoffeeshop-charts
      overrides:
        - name: projectnamespace
          value: quarkuscoffeeshop-demo
        - name: Release.release-namespace
          value: quarkuscoffeeshop-demo
        - name: storeid
          value: TEST

    coffeeshopdb-test:
      name: quarkuscoffeeshopdb-demo
      namespace: quarkuscoffeeshop-demo
      project: quarkuscoffeeshop-demo
      path: charts/all/crunchy-pgcluster
      extraValueFiles:
        - /values-db-store.yaml

    coffeeshop-test-kafka:
      name: coffeeshop-test-kafka
      namespace: quarkuscoffeeshop-demo
      project: quarkuscoffeeshop-demo
      path: charts/all/quarkuscoffeeshop-kafka
      overrides:
        - name: mirrorMaker.enabled
          value: "false"

    # Store site "ATLANTA"
    coffeeshop-store:
      name: coffeeshop-store
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/store/quarkuscoffeeshop-charts
      overrides:
        - name: projectnamespace
          value: coffeeshop-store
        - name: Release.release-namespace
          value: coffeeshop-store
        - name: storeid
          value: ATLANTA

    coffeeshopdb-store:
      name: coffeeshopdb-store
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/all/crunchy-pgcluster
      extraValueFiles:
        - /values-db-store.yaml

    coffeeshop-store-kafka:
      name: coffeeshop-store-kafka
      namespace: coffeeshop-store
      project: coffeeshop-store
      path: charts/all/quarkuscoffeeshop-kafka
      overrides:
        - name: clusterGroup.isHubCluster
          value: "false"
        - name: mirrorMaker.enabled
          value: "false"

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs: []
    #- name: noop
      # ansible playbook to be run
    #  playbook: ansible/playbooks/noop.yml
      # per playbook timeout in seconds
   #   timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    raleigh:
      name: raleigh
      helmOverrides:
      # Values must be strings!
      - name: clusterGroup.isHubCluster
        value: "false"
      clusterSelector:
        matchLabels:
          clusterGroup: raleigh
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift
