---
clusterName: db

postgresVersion: 16

clusterUsers:
  - name: user
    databases:
      - db

dbInitConfigMap:
  name: db-init-sql
  key: initSQL

dbInitSQL: |-
  \c db;

clusterInstances:
  - name: instance1
    dataVolumeClaimSpec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi

enablePgAdmin: false
pgAdmin:
  replicas: 1
  service:
    type: ClusterIP
  dataVolumeClaimSpec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 1Gi

pgbackrest:
  repos:
    - name: repo1
      volume:
        volumeClaimSpec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 1Gi
