apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafkaClusterName }}
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    version: {{ .Values.kafkaVersion }}
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
{{- if .Values.clusterGroup.isHubCluster }}
        type: route
{{- else }}
        type: internal
{{- end }}
        tls: true
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: {{ .Values.kafkaInterBrokerVersion }}
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
